# Simulation Exercise

In [1]:
import numpy as np
import pandas as pd

np.random.seed(3)

## P(doubles when rolling 2 dice)

In [12]:
rolls = np.random.randint(1, 7, (10_000, 2))
rolls

array([[5, 5],
       [2, 1],
       [1, 4],
       ...,
       [3, 3],
       [6, 5],
       [2, 1]])

In [11]:
(rolls[:, 0] == rolls[:, 1]).mean()

0.1711

## P(3 heads in 8 coin tosses)

In [13]:
flips = np.random.choice(['Heads', 'Tails'], (10_000, 8))
flips

array([['Heads', 'Heads', 'Tails', ..., 'Tails', 'Tails', 'Tails'],
       ['Heads', 'Heads', 'Heads', ..., 'Heads', 'Heads', 'Tails'],
       ['Tails', 'Heads', 'Heads', ..., 'Heads', 'Tails', 'Heads'],
       ...,
       ['Heads', 'Tails', 'Heads', ..., 'Heads', 'Tails', 'Tails'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Heads', 'Heads'],
       ['Heads', 'Tails', 'Heads', ..., 'Tails', 'Tails', 'Tails']],
      dtype='<U5')

In [16]:
((flips == 'Heads').sum(axis=1) == 3)

array([ True, False, False, ...,  True,  True, False])

In [17]:
((flips == 'Heads').sum(axis=1) > 3).mean()

0.6353

## 2 DS students on billboards

In [25]:
[1, 2, 3] * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [26]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [18]:
options = ['Web Dev'] * 3 + ['Data Science']
options

['Web Dev', 'Web Dev', 'Web Dev', 'Data Science']

In [36]:
(np.random.choice(options, (10_000, 5)) == 'Data Science').prod(axis=1).mean()

0.0011

In [22]:
(np.random.choice(options, (10_000, 2)) == 'Data Science').sum(axis=1) == 2

array([False, False, False, ..., False, False, False])

In [23]:
(((np.random.choice(options, (10_000, 2)) == 'Data Science').sum(axis=1)) == 2).mean()

0.058

## Poptarts

In [56]:
n = 10_000

pt_consumption = np.round(np.random.normal(3, 1.5, (n, 5)))
pt_consumption

array([[-0.,  5.,  4.,  1.,  5.],
       [ 5.,  2.,  5.,  4.,  1.],
       [ 2.,  0.,  2.,  5.,  2.],
       ...,
       [ 2.,  1.,  2.,  1.,  3.],
       [ 3.,  0., -1.,  1.,  2.],
       [ 1.,  3.,  1.,  5.,  1.]])

In [65]:
np.where(pt_consumption < 0, 0, pt_consumption)

array([[-0.,  5.,  4.,  1.,  5.],
       [ 5.,  2.,  5.,  4.,  1.],
       [ 2.,  0.,  2.,  5.,  2.],
       ...,
       [ 2.,  1.,  2.,  1.,  3.],
       [ 3.,  0.,  0.,  1.,  2.],
       [ 1.,  3.,  1.,  5.,  1.]])

In [66]:
pt_consumption = np.where(pt_consumption < 0, 0, pt_consumption)
(pt_consumption.sum(axis=1) < 17).mean()

0.6709

## compare heights

In [70]:
n = 10_000

male_heights = np.random.normal(178, 8, n)
female_heights = np.random.normal(170, 6, n)

male_heights
female_heights

array([169.80408143, 169.52673834, 181.07761992, ..., 169.12308228,
       166.75473152, 164.6022895 ])

In [6]:
(female_heights > male_heights).mean()

0.2152

## anaconda install

In [ ]:
n = 10_000

p_corruption = 1/250

In [80]:
((np.random.random((n, 50)) < p_corruption).sum(axis=1) == 0).mean()

0.8191

In [85]:
((np.random.random((n, 100)) <= p_corruption).sum(axis=1) == 0).mean()

0.6687

In [86]:
# 1 - ((np.random.random((n, 50)) < p_corruption).sum(axis=1) > 0).mean()
# 1 - ((np.random.random((n, 100)) < p_corruption).sum(axis=1) > 0).mean()



((np.random.random((n, 150)) < p_corruption).sum(axis=1) > 0).mean()



# 1 - ((np.random.random((n, 450)) < p_corruption).sum(axis=1) > 0).mean()

0.4601

In [103]:
# alternate way to simulate success vs corrupted download
downloads = np.random.choice(['Download Success', 'Corrupted!'], (n, 450), p=[249/250, 1/250])

((downloads == 'Corrupted!').sum(axis=1) == 0).mean()

0.1629

## food trucks

In [104]:
n = 10_000
p_food_truck = .7
p_no_food_truck = 1 - p_food_truck

In [114]:
lunches = np.random.choice(['Food Truck', 'No Food Truck'], (n, 3), p=[p_food_truck, p_no_food_truck])
lunches

array([['Food Truck', 'Food Truck', 'No Food Truck'],
       ['Food Truck', 'No Food Truck', 'Food Truck'],
       ['Food Truck', 'Food Truck', 'Food Truck'],
       ...,
       ['Food Truck', 'Food Truck', 'Food Truck'],
       ['Food Truck', 'Food Truck', 'No Food Truck'],
       ['Food Truck', 'Food Truck', 'Food Truck']], dtype='<U13')

In [117]:
lunches == 'No Food Truck'

array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       ...,
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [119]:
(lunches == 'No Food Truck').all(axis=1).mean()

0.0277

In [120]:
lunches = np.random.choice(['Food Truck', 'No Food Truck'], (n, 5), p=[p_food_truck, p_no_food_truck])
lunches

array([['No Food Truck', 'No Food Truck', 'Food Truck', 'Food Truck',
        'Food Truck'],
       ['Food Truck', 'Food Truck', 'No Food Truck', 'Food Truck',
        'Food Truck'],
       ['Food Truck', 'Food Truck', 'Food Truck', 'No Food Truck',
        'Food Truck'],
       ...,
       ['Food Truck', 'Food Truck', 'No Food Truck', 'No Food Truck',
        'Food Truck'],
       ['Food Truck', 'Food Truck', 'Food Truck', 'Food Truck',
        'No Food Truck'],
       ['Food Truck', 'No Food Truck', 'Food Truck', 'Food Truck',
        'Food Truck']], dtype='<U13')

In [123]:
(lunches == 'Food Truck').any(axis=1).mean()

0.9978

In [8]:
# ((np.random.random((n, 3)) < p_food_truck).sum(axis=1) == 0).mean()
# ((np.random.random((n, 5)) < p_food_truck).sum(axis=1) > 0).mean()

0.998

In [ ]:
np.random.choice([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

## birthdays

In [125]:
row = np.random.choice(range(365), 23)
row

array([284, 108, 199, 291,  78, 302, 294, 336, 297, 244, 144, 235, 205,
        25, 152,  10, 286,  94, 270,  50, 162,  91, 226])

In [127]:
np.unique(np.array([1, 2, 3, 2, 2, 2]))

array([1, 2, 3])

In [168]:
np.random.choice(range(365), 23)
np.unique(row).size < 23

False

In [170]:
birthdays = np.random.choice(range(365), (n_sims, n_people))
birthdays

array([[ 55, 280, 307, ...,  10, 279, 204],
       [ 69, 259,  32, ..., 110, 282, 227],
       [ 19, 139, 231, ...,  81,  90, 287],
       ...,
       [205, 105,   4, ..., 105, 260, 245],
       [121, 117, 279, ..., 161,  12,  75],
       [179,  46, 111, ...,  58, 137, 309]])

In [171]:
[np.unique(row).size for row in birthdays]

[22,
 23,
 23,
 22,
 22,
 23,
 23,
 22,
 22,
 23,
 22,
 23,
 23,
 23,
 21,
 22,
 22,
 23,
 22,
 23,
 22,
 23,
 23,
 22,
 22,
 22,
 23,
 22,
 21,
 22,
 23,
 22,
 23,
 21,
 22,
 23,
 22,
 23,
 20,
 23,
 22,
 22,
 20,
 23,
 23,
 23,
 23,
 22,
 23,
 22,
 22,
 21,
 22,
 23,
 22,
 23,
 22,
 22,
 23,
 22,
 22,
 23,
 22,
 23,
 21,
 23,
 23,
 22,
 23,
 21,
 22,
 23,
 23,
 23,
 23,
 23,
 23,
 22,
 22,
 22,
 21,
 22,
 23,
 22,
 23,
 23,
 23,
 21,
 22,
 23,
 21,
 23,
 22,
 23,
 22,
 23,
 22,
 22,
 22,
 23,
 23,
 22,
 21,
 22,
 22,
 23,
 21,
 22,
 23,
 22,
 20,
 23,
 23,
 22,
 21,
 21,
 22,
 22,
 22,
 22,
 22,
 23,
 23,
 21,
 23,
 23,
 23,
 23,
 22,
 23,
 23,
 23,
 22,
 23,
 23,
 23,
 23,
 23,
 22,
 23,
 21,
 22,
 23,
 22,
 22,
 21,
 22,
 23,
 23,
 21,
 22,
 23,
 21,
 23,
 23,
 21,
 21,
 23,
 23,
 23,
 23,
 21,
 22,
 23,
 21,
 23,
 21,
 22,
 21,
 21,
 23,
 21,
 21,
 23,
 23,
 22,
 22,
 23,
 23,
 23,
 23,
 22,
 23,
 22,
 23,
 22,
 22,
 23,
 23,
 22,
 23,
 21,
 22,
 23,
 23,
 22,
 22,
 22,
 22,
 22,


In [178]:
n_sims = 10_000
n_people = 29

birthdays = np.random.choice(range(365), (n_sims, n_people))

n_unique_birthdays = np.array([np.unique(row).size for row in birthdays])

(n_unique_birthdays < n_people).mean()

0.6749

In [185]:
s = pd.DataFrame(birthdays).iloc[0, :]
s

0     261
1     127
2     138
3      20
4     299
5     226
6      26
7     248
8     279
9     155
10    210
11    341
12    313
13     74
14    182
15    330
16    114
17     12
18    276
19      3
20    137
21    127
22    280
23    286
24    262
25    230
26    309
27     52
28    120
Name: 0, dtype: int64

In [186]:
s.nunique()

28

In [190]:
(pd.DataFrame(birthdays).apply(lambda s: s.nunique(), axis=1) < 29).mean()

0.6749

In [192]:
(pd.DataFrame(birthdays).nunique(axis=1) < 29).mean()

0.6749